# Generated by Django 4.2.4 on 2023-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('1', 'Uttar Pradesh'), ('2', 'Madhya Pradesh'), ('3', 'Maharashtra'), ('4', 'Rajasthan'), ('5', 'Bihar'), ('6', 'West Bengal'), ('7', 'Andhra Pradesh'), ('8', 'Tamil Nadu'), ('9', 'Karnataka'), ('10', 'Gujarat'), ('11', 'Odisha'), ('12', 'Telangana'), ('13', 'Kerala'), ('14', 'Jharkhand'), ('15', 'Assam'), ('16', 'Punjab'), ('17', 'Chhattisgarh'), ('18', 'Haryana'), ('19', 'Uttarakhand'), ('20', 'Himachal Pradesh'), ('21', 'Tripura'), ('22', 'Meghalaya'), ('23', 'Manipur'), ('24', 'Nagaland'), ('25', 'Goa'), ('26', 'Arunachal Pradesh'), ('27', 'Mizoram'), ('28', 'Sikkim')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
